travis:
  secure:
    BINSTAR_TOKEN: AUp3LgUrr0599uLpz2XKrPrtso3qc4Y5nqIAnua7vtSBmD8fghQL+9LYIhKForqZcKiBGWgfmhQ9Zfx5BJDb2/u786+LZkGRd60tF9qklrV/miQhQ9JCFZe+jPM4p/d23sL1fKcuVpW+Z7cKfSH0X9+4r3Ym/aKf44gVEzu2bOsfIH5g//YScWNNILFRbfJP7lBCuKUu59EJ/HWUj1xrtzqvNzJEOUoMLMiXYT4rtQiKeg7glSGerlzNicNAnP76XV0GDbnubTdFbV4YQ8nPuiOrnmF42I4a7h3+JKQJpu8vFRIRTRqzJLFkkP2Y77wB357nIzCw9f10/W/SG7N00ftRD2IyJTHFCSl9jIrPFKPCb1SW/xu3A16hO7Ets0QrrTp5nVEn9QcDZF9XUy2DLW/S0cU0liUTDvAwDVkdYZVcaZ78StkjxjEFgKOe1+IjbajYFle5ZTFs1ogNNJ3LNef54ppLtlEDqpDZ6bX7fhxt/6FUVhZrQUZqoaQsco/SUgwSoNxezQeV2IR5AM+C+TCGL7SUiX3vf/t0M8aNXWPtHh1kyAya7qnjLNqwgZKiUIcyKReZNmWocmD5ny+ZshABDAh671jbkDEV5Yai+o/+LayOmdPwkegevjXqy3odpV/KSSgwoa0G6sVZR+Ds34LEr5f+FAYOWmbQgC+vxeU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
